variables:
    GIT_SUBMODULE_STRATEGY: recursive

stages:
- build

.cache-paths-spec: &cache-paths
- build

.linux-cache-spec-template: &linux-cache-spec
  cache:
    key: ${CI_COMMIT_REF_SLUG}-${CI_JOB_NAME}
    paths: *cache-paths

.windows-cache-spec-template: &windows-cache-spec
  cache:
    paths: *cache-paths
    key: "%CI_COMMIT_REF_SLUG%-%CI_JOB_NAME%-%CI_RUNNER_ID%"

.linux-build-template: &linux-build-task
  stage: build
  <<: *linux-cache-spec
  script:
  - cmake -E make_directory build
  - cd build
  - cmake -G Ninja -DCMAKE_BUILD_TYPE=${BUILD_TYPE} -DSTRUCTOCOL_FORCE_DISABLE_ASIO_SUPPORT=${DISABLE_ASIO_SUPPORT} ..
  - cmake --build .
  - ctest --output-on-failure
  only:
    variables:
    - $CI_BUILD_IMAGE_BASE

.mingw-build-template: &mingw-build-task
  stage: build
  <<: *windows-cache-spec    
  tags:
  - win-cpp
  only:
    variables:
    - $WINDOWS_CI
  script:
  - cmake -E make_directory build
  - cd build
  - cmake -G Ninja -DCMAKE_BUILD_TYPE=%BUILD_TYPE% -DSTRUCTOCOL_FORCE_DISABLE_ASIO_SUPPORT=%DISABLE_ASIO_SUPPORT% ..
  - cmake --build .
  - ctest --output-on-failure

.msbuild-build-template: &msbuild-build-task
  stage: build
  <<: *windows-cache-spec    
  tags:
  - win-cpp
  only:
    variables:
    - $WINDOWS_CI
  script:
  - cmake -E make_directory build
  - cd build
  - cmake -G "Visual Studio 15 2017" -A x64 -DSTRUCTOCOL_FORCE_DISABLE_ASIO_SUPPORT=%DISABLE_ASIO_SUPPORT% ..
  - cmake --build . --config %BUILD_TYPE% 
  - ctest -C %BUILD_TYPE% --output-on-failure

gcc-debug-build:
  variables:
    CXX: "g++"
    CC: "gcc"
    BUILD_TYPE: "Debug"
    DISABLE_ASIO_SUPPORT: "OFF"
  image: ${CI_BUILD_IMAGE_BASE}${CI_BUILD_IMAGE_SUFFIX_GCC_DEBUG}
  <<: *linux-build-task

gcc-release-build:
  variables:
    CXX: "g++"
    CC: "gcc"
    BUILD_TYPE: "Release"
    DISABLE_ASIO_SUPPORT: "OFF"
  image: ${CI_BUILD_IMAGE_BASE}${CI_BUILD_IMAGE_SUFFIX_GCC_RELEASE}
  <<: *linux-build-task

clang-debug-build:
  variables:
    CXX: "clang++"
    CC: "clang"
    BUILD_TYPE: "Debug"
    DISABLE_ASIO_SUPPORT: "OFF"
    CXXFLAGS: "-stdlib=libc++"
    LDFLAGS: "-stdlib=libc++"
  image: ${CI_BUILD_IMAGE_BASE}${CI_BUILD_IMAGE_SUFFIX_CLANG_DEBUG}
  <<: *linux-build-task

clang-release-build:
  variables:
    CXX: "clang++"
    CC: "clang"
    BUILD_TYPE: "Release"
    DISABLE_ASIO_SUPPORT: "OFF"
    CXXFLAGS: "-stdlib=libc++"
    LDFLAGS: "-stdlib=libc++"
  image: ${CI_BUILD_IMAGE_BASE}${CI_BUILD_IMAGE_SUFFIX_CLANG_RELEASE}
  <<: *linux-build-task

gcc-debug-build-noasio:
  variables:
    CXX: "g++"
    CC: "gcc"
    BUILD_TYPE: "Debug"
    DISABLE_ASIO_SUPPORT: "ON"
  image: ${CI_BUILD_IMAGE_BASE}${CI_BUILD_IMAGE_SUFFIX_GCC_DEBUG}
  <<: *linux-build-task

clang-debug-build-noasio:
  variables:
    CXX: "clang++"
    CC: "clang"
    BUILD_TYPE: "Debug"
    DISABLE_ASIO_SUPPORT: "ON"
    CXXFLAGS: "-stdlib=libc++"
    LDFLAGS: "-stdlib=libc++"
  image: ${CI_BUILD_IMAGE_BASE}${CI_BUILD_IMAGE_SUFFIX_CLANG_DEBUG}
  <<: *linux-build-task

clang-asan-ubsan-build:
  variables:
    CXX: "clang++"
    CC: "clang"
    BUILD_TYPE: "Debug"
    LDFLAGS: "-stdlib=libc++ -fno-omit-frame-pointer -fsanitize=address -fsanitize=undefined -fsanitize-address-use-after-scope"
    CXXFLAGS: "-stdlib=libc++ -fno-omit-frame-pointer -fsanitize=address -fsanitize=undefined -fsanitize-address-use-after-scope"
    LSAN_OPTIONS: "detect_leaks=0:verbosity=1:log_threads=1:check_initialization_order=1:detect_stack_use_after_return=1"
  image: ${CI_BUILD_IMAGE_BASE}${CI_BUILD_IMAGE_SUFFIX_CLANG_DEBUG}
  <<: *linux-build-task

clang-tidy-lint:
  stage: build
  <<: *linux-cache-spec
  script:
  - cmake -E make_directory build
  - cd build
  - cmake -G Ninja "-DCMAKE_CXX_CLANG_TIDY=/usr/bin/clang-tidy" -DCMAKE_BUILD_TYPE=Debug -DBoost_USE_STATIC_LIBS=ON ..
  - cmake --build . --clean-first
  image: ${CI_BUILD_IMAGE_BASE}${CI_BUILD_IMAGE_SUFFIX_CLANG_DEBUG}
  only:
    variables:
    - $CI_BUILD_IMAGE_BASE
  allow_failure: true

msvc-debug-build:
  variables:
    BUILD_TYPE: "Debug"
    DISABLE_ASIO_SUPPORT: "OFF"
  <<: *msbuild-build-task

msvc-release-build:
  variables:
    BUILD_TYPE: "Release"
    DISABLE_ASIO_SUPPORT: "OFF"
  <<: *msbuild-build-task

mingw-debug-build:
  variables:
    BUILD_TYPE: "Debug"
    DISABLE_ASIO_SUPPORT: "OFF"
  <<: *mingw-build-task

mingw-release-build:
  variables:
    BUILD_TYPE: "Release"
    DISABLE_ASIO_SUPPORT: "OFF"
  <<: *mingw-build-task

msvc-debug-build-noasio:
  variables:
    BUILD_TYPE: "Debug"
    DISABLE_ASIO_SUPPORT: "ON"
  <<: *msbuild-build-task

mingw-debug-build-noasio:
  variables:
    BUILD_TYPE: "Debug"
    DISABLE_ASIO_SUPPORT: "ON"
  <<: *mingw-build-task
