variables:
    GIT_SUBMODULE_STRATEGY: recursive

stages:
- build

include:
- template: 'Workflows/Branch-Pipelines.gitlab-ci.yml'
- local: '/Cache.gitlab-ci.yml'
- local: '/Templates.gitlab-ci.yml'

gcc-debug-build:
  extends: .linux-build-job
  variables:
    CXX: "g++"
    CC: "gcc"
    BUILD_TYPE: "Debug"
    DISABLE_ASIO_SUPPORT: "OFF"
    TEST_CPP20_SUPPORT: "ON"
  image: ${BUILD_IMAGE_BASE}${BUILD_IMAGE_SUFFIX_GCC_DEBUG}

gcc-release-build:
  extends: .linux-build-job
  variables:
    CXX: "g++"
    CC: "gcc"
    BUILD_TYPE: "Release"
    DISABLE_ASIO_SUPPORT: "OFF"
    TEST_CPP20_SUPPORT: "ON"
  image: ${BUILD_IMAGE_BASE}${BUILD_IMAGE_SUFFIX_GCC_RELEASE}

gcc-debug-build-noasio:
  extends: .linux-build-job
  variables:
    CXX: "g++"
    CC: "gcc"
    BUILD_TYPE: "Debug"
    DISABLE_ASIO_SUPPORT: "ON"
    TEST_CPP20_SUPPORT: "ON"
  image: ${BUILD_IMAGE_BASE}${BUILD_IMAGE_SUFFIX_GCC_DEBUG}

gcc-debug-build-cpp17:
  extends: .linux-build-job
  variables:
    CXX: "g++"
    CC: "gcc"
    BUILD_TYPE: "Debug"
    DISABLE_ASIO_SUPPORT: "OFF"
    TEST_CPP20_SUPPORT: "OFF"
  image: ${BUILD_IMAGE_BASE}${BUILD_IMAGE_SUFFIX_GCC_DEBUG}

clang-debug-build:
  extends: .linux-build-job
  variables:
    CXX: "clang++"
    CC: "clang"
    BUILD_TYPE: "Debug"
    DISABLE_ASIO_SUPPORT: "OFF"
    TEST_CPP20_SUPPORT: "ON"
    CXXFLAGS: "-stdlib=libc++"
    LDFLAGS: "-stdlib=libc++"
  image: ${BUILD_IMAGE_BASE}${BUILD_IMAGE_SUFFIX_CLANG_DEBUG}

clang-release-build:
  extends: .linux-build-job
  variables:
    CXX: "clang++"
    CC: "clang"
    BUILD_TYPE: "Release"
    DISABLE_ASIO_SUPPORT: "OFF"
    TEST_CPP20_SUPPORT: "ON"
    CXXFLAGS: "-stdlib=libc++"
    LDFLAGS: "-stdlib=libc++"
  image: ${BUILD_IMAGE_BASE}${BUILD_IMAGE_SUFFIX_CLANG_RELEASE}

clang-debug-build-noasio:
  extends: .linux-build-job
  variables:
    CXX: "clang++"
    CC: "clang"
    BUILD_TYPE: "Debug"
    DISABLE_ASIO_SUPPORT: "ON"
    TEST_CPP20_SUPPORT: "ON"
    CXXFLAGS: "-stdlib=libc++"
    LDFLAGS: "-stdlib=libc++"
  image: ${BUILD_IMAGE_BASE}${BUILD_IMAGE_SUFFIX_CLANG_DEBUG}

clang-debug-build-cpp17:
  extends: .linux-build-job
  variables:
    CXX: "clang++"
    CC: "clang"
    BUILD_TYPE: "Debug"
    DISABLE_ASIO_SUPPORT: "OFF"
    TEST_CPP20_SUPPORT: "OFF"
    CXXFLAGS: "-stdlib=libc++"
    LDFLAGS: "-stdlib=libc++"
  image: ${BUILD_IMAGE_BASE}${BUILD_IMAGE_SUFFIX_CLANG_DEBUG}

clang-asan-ubsan-build:
  extends: .linux-build-job
  variables:
    CXX: "clang++"
    CC: "clang"
    BUILD_TYPE: "Debug"
    TEST_CPP20_SUPPORT: "ON"
    LDFLAGS: "-stdlib=libc++ -fno-omit-frame-pointer -fsanitize=address -fsanitize=undefined -fsanitize-address-use-after-scope"
    CXXFLAGS: "-stdlib=libc++ -fno-omit-frame-pointer -fsanitize=address -fsanitize=undefined -fsanitize-address-use-after-scope"
    LSAN_OPTIONS: "detect_leaks=0:verbosity=1:log_threads=1:check_initialization_order=1:detect_stack_use_after_return=1"
  image: ${BUILD_IMAGE_BASE}${BUILD_IMAGE_SUFFIX_CLANG_DEBUG}

clang-tidy-lint:
  stage: build
  extends: .linux-cache-specs
  script:
  - cmake -E make_directory build
  - cd build
  - cmake -G Ninja "-DCMAKE_CXX_CLANG_TIDY=/usr/bin/clang-tidy" -DCMAKE_BUILD_TYPE=Debug -DBoost_USE_STATIC_LIBS=ON ..
  - cmake --build . --clean-first
  variables:
    CXX: "clang++"
    CC: "clang"
    BUILD_TYPE: "Debug"
    DISABLE_ASIO_SUPPORT: "OFF"
    TEST_CPP20_SUPPORT: "ON"
    CXXFLAGS: "-stdlib=libc++"
    LDFLAGS: "-stdlib=libc++"
  image: ${BUILD_IMAGE_BASE}${BUILD_IMAGE_SUFFIX_CLANG_DEBUG}
  rules:
  - if: '$BUILD_IMAGE_BASE'
  allow_failure: true

msvc-debug-build:
  variables:
    BUILD_TYPE: "Debug"
    DISABLE_ASIO_SUPPORT: "OFF"
    TEST_CPP20_SUPPORT: "ON"
  extends: .msbuild-build-job

msvc-release-build:
  variables:
    BUILD_TYPE: "Release"
    DISABLE_ASIO_SUPPORT: "OFF"
    TEST_CPP20_SUPPORT: "ON"
  extends: .msbuild-build-job

msvc-debug-build-noasio:
  variables:
    BUILD_TYPE: "Debug"
    DISABLE_ASIO_SUPPORT: "ON"
    TEST_CPP20_SUPPORT: "ON"
  extends: .msbuild-build-job

msvc-debug-build-cpp17:
  variables:
    BUILD_TYPE: "Debug"
    DISABLE_ASIO_SUPPORT: "OFF"
    TEST_CPP20_SUPPORT: "OFF"
  extends: .msbuild-build-job

mingw-debug-build:
  variables:
    BUILD_TYPE: "Debug"
    DISABLE_ASIO_SUPPORT: "OFF"
    TEST_CPP20_SUPPORT: "OFF"
  extends: .mingw-build-job

mingw-release-build:
  variables:
    BUILD_TYPE: "Release"
    DISABLE_ASIO_SUPPORT: "OFF"
    TEST_CPP20_SUPPORT: "OFF"
  extends: .mingw-build-job

mingw-debug-build-noasio:
  variables:
    BUILD_TYPE: "Debug"
    DISABLE_ASIO_SUPPORT: "ON"
    TEST_CPP20_SUPPORT: "OFF"
  extends: .mingw-build-job
