.cache-specs:
  cache:
    paths:
    - build

.linux-cache-specs:
  extends: .cache-specs
  cache:
    key: ${CI_COMMIT_REF_SLUG}-${CI_JOB_NAME}

.windows-cache-specs:
  extends: .cache-specs
  cache:
    key: "${CI_COMMIT_REF_SLUG}-${CI_JOB_NAME}-${CI_RUNNER_ID}"

