include: '/Cache.gitlab-ci.yml'

.linux-build-job:
  stage: build
  extends: .linux-cache-specs
  script:
  - cmake -E make_directory build
  - cd build
  - cmake -G Ninja -DCMAKE_BUILD_TYPE=${BUILD_TYPE} -DSTRUCTOCOL_FORCE_DISABLE_ASIO_SUPPORT=${DISABLE_ASIO_SUPPORT} ..
  - cmake --build .
  - ctest --output-on-failure
  rules:
  - if: '$BUILD_IMAGE_BASE'

.mingw-build-job:
  stage: build
  extends: .windows-cache-specs
  tags:
  - win-cpp
  rules:
  - if: '$WINDOWS_CI'
  script:
  - cmake -E make_directory build
  - cd build
  - cmake -G Ninja -DCMAKE_BUILD_TYPE=$env:BUILD_TYPE -DSTRUCTOCOL_FORCE_DISABLE_ASIO_SUPPORT=$env:DISABLE_ASIO_SUPPORT ..
  - cmake --build .
  - ctest --output-on-failure

.msbuild-build-job:
  stage: build
  extends: .windows-cache-specs
  tags:
  - win-cpp
  rules:
  - if: '$WINDOWS_CI'
  script:
  - cmake -E make_directory build
  - cd build
  - cmake -G "Visual Studio 16 2019" -A x64 -DSTRUCTOCOL_FORCE_DISABLE_ASIO_SUPPORT=$env:DISABLE_ASIO_SUPPORT ..
  - cmake --build . --config $env:BUILD_TYPE
  - ctest -C $env:BUILD_TYPE --output-on-failure

